-- MySQL Script generated by MySQL Workbench
-- Fri 05 Aug 2016 07:20:00 PM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yamdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yamdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yamdb` DEFAULT CHARACTER SET utf8 ;
USE `yamdb` ;

-- -----------------------------------------------------
-- Table `yamdb`.`Ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yamdb`.`Ratings` (
  `MovieID` INT NOT NULL,
  `Distribution` VARCHAR(10) NULL,
  `Votes` INT NULL,
  `Rank` TINYINT NULL,
  `Title` VARCHAR(200) NULL,
  `Year` YEAR NULL,
  PRIMARY KEY (`MovieID`),
  INDEX `Search` (`Title` ASC, `Year` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yamdb`.`Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yamdb`.`Genres` (
  `MovieID` INT NULL,
  `Title` VARCHAR(200) NULL,
  `Year` YEAR NULL,
  `Genre` VARCHAR(20) NULL,
  INDEX `Search` (`Title` ASC, `Year` ASC),
  FULLTEXT INDEX `Genres` (`Genre` ASC),
  INDEX `fk_Genres_idx` (`MovieID` ASC),
  CONSTRAINT `fk_Genres`
    FOREIGN KEY (`MovieID`)
    REFERENCES `yamdb`.`Ratings` (`MovieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yamdb`.`ProductionCompanies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yamdb`.`ProductionCompanies` (
  `MovieID` INT NULL,
  `Title` VARCHAR(200) NULL,
  `Year` YEAR NULL,
  `ProductionCompany` VARCHAR(200) NULL,
  INDEX `Search` (`Title` ASC, `Year` ASC),
  INDEX `fk_ProductionCompanies_idx` (`MovieID` ASC),
  CONSTRAINT `fk_ProductionCompanies`
    FOREIGN KEY (`MovieID`)
    REFERENCES `yamdb`.`Ratings` (`MovieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yamdb`.`Actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yamdb`.`Actors` (
  `ActorID` INT NULL,
  `Name` VARCHAR(100) NULL,
  `Gender` CHAR(1) NULL,
  `MovieID` INT NULL,
  `Title` VARCHAR(200) NULL,
  `Year` YEAR NULL,
  INDEX `Search` (`Title` ASC, `Year` ASC),
  INDEX `Lookup_ActorID` (`ActorID` ASC),
  INDEX `Lookup_Name` (`Name` ASC),
  INDEX `Lookup_MovieID` (`MovieID` ASC),
  CONSTRAINT `fk_Actors`
    FOREIGN KEY ()
    REFERENCES `yamdb`.`Ratings` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'USERNAME' IDENTIFIED BY 'PASSWORD';

GRANT ALL ON `yamdb`.* TO 'USERNAME';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
